version: 2.1

orbs:
 win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default     

    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release
      - run: 
          name: Pack build result 
          command: Compress-Archive -Path TowerOfDoom\bin\Release\* -DestinationPath build.zip
      - store_artifacts: 
          path: build.zip