name: 🆕 Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if a similar feature has already been requested.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your request related to a problem?
    description: | 
      Provide a clear and concise description of what the problem is.
      Ex. I have an issue when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: Provide a clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: Let us know about other solutions you've tried or researched.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
